name: lint
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2

    - name: Install dependencies
      run: bundle install

    - name: Lint
      run: rubocop --format tap -o rubocop.txt

    - uses: actions/upload-artifact@v2
      with:
        name: rspec.txt
        path: rspec.txt
